/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Revilo
 */
public class NuevoTanque extends javax.swing.JFrame {

    /**
     * Creates new form NuevoTanque
     */
    public NuevoTanque() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tipoDeTanque = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        m1 = new javax.swing.JTextField();
        m2 = new javax.swing.JTextField();
        m3 = new javax.swing.JTextField();
        m4 = new javax.swing.JTextField();
        m5 = new javax.swing.JTextField();
        m6 = new javax.swing.JTextField();
        m7 = new javax.swing.JTextField();
        m8 = new javax.swing.JTextField();
        m9 = new javax.swing.JTextField();
        m10 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        largo = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        ancho = new javax.swing.JTextField();
        altura = new javax.swing.JTextField();
        radio = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        guardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Seleccione la forma del Tanque");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 40, -1, -1));

        tipoDeTanque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tanque Cilindrico", "Tanque Cubico", "Tanque Ortogonal", " " }));
        tipoDeTanque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoDeTanqueActionPerformed(evt);
            }
        });
        getContentPane().add(tipoDeTanque, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 36, -1, -1));

        jLabel4.setText("Ingrese la información correspondiente:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 170, -1, -1));

        jLabel5.setText("Municipio");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 198, -1, -1));
        getContentPane().add(m1, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 220, 141, -1));

        m2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m2ActionPerformed(evt);
            }
        });
        getContentPane().add(m2, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 252, 141, -1));
        getContentPane().add(m3, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 284, 141, -1));

        m4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m4ActionPerformed(evt);
            }
        });
        getContentPane().add(m4, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 316, 141, -1));
        getContentPane().add(m5, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 348, 141, -1));
        getContentPane().add(m6, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 383, 141, -1));
        getContentPane().add(m7, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 415, 141, -1));
        getContentPane().add(m8, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 447, 141, -1));
        getContentPane().add(m9, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 479, 141, -1));
        getContentPane().add(m10, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 511, 141, -1));

        jLabel2.setText("Válvula 1");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 225, -1, -1));

        jLabel3.setText("Válvula 2");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 257, -1, -1));

        jLabel7.setText("Válvula 3");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 289, -1, -1));

        jLabel8.setText("Válvula 4");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 321, -1, -1));

        jLabel9.setText("Válvula 5");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 353, -1, -1));

        jLabel10.setText("Válvula 6");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 388, -1, -1));

        jLabel11.setText("Válvula 7");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 420, -1, -1));

        jLabel12.setText("Válvula 8");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 452, -1, -1));

        jLabel13.setText("Válvula 9");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 484, -1, -1));

        jLabel14.setText("Válvula 10");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 516, -1, -1));

        jLabel15.setText("Largo");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 74, -1, -1));
        getContentPane().add(largo, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 69, 94, -1));

        jLabel16.setText("Ancho");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 118, -1, -1));

        ancho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anchoActionPerformed(evt);
            }
        });
        getContentPane().add(ancho, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 113, 95, -1));
        getContentPane().add(altura, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 69, 84, -1));
        getContentPane().add(radio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 113, 84, -1));

        jLabel17.setText("Altura");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 74, -1, -1));

        jLabel18.setText("Radio");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 118, -1, -1));

        guardar.setText("Guardar");
        getContentPane().add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 348, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipoDeTanqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoDeTanqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoDeTanqueActionPerformed

    private void m2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m2ActionPerformed

    private void m4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m4ActionPerformed

    private void anchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anchoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anchoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoTanque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoTanque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoTanque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoTanque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoTanque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField altura;
    private javax.swing.JTextField ancho;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField largo;
    private javax.swing.JTextField m1;
    private javax.swing.JTextField m10;
    private javax.swing.JTextField m2;
    private javax.swing.JTextField m3;
    private javax.swing.JTextField m4;
    private javax.swing.JTextField m5;
    private javax.swing.JTextField m6;
    private javax.swing.JTextField m7;
    private javax.swing.JTextField m8;
    private javax.swing.JTextField m9;
    private javax.swing.JTextField radio;
    private javax.swing.JComboBox<String> tipoDeTanque;
    // End of variables declaration//GEN-END:variables
}
